In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, precision_score, recall_score

In [3]:
df = pd.read_csv("customer_purchase.csv")

df.head()

   Age  Income  PreviousPurchases  Purchase
0   22   25000                  1         0
1   25   30000                  2         0
2   28   35000                  3         0
3   30   40000                  4         1
4   32   45000                  5         1

In [4]:
print("Shape of dataset:", df.shape)

print("\nColumn names:")
print(df.columns)

print("\nMissing values:")
print(df.isnull().sum())

Shape of dataset: (100, 4)

Column names:
Index(['Age', 'Income', 'PreviousPurchases', 'Purchase'], dtype='str')

Missing values:
Age                  0
Income               0
PreviousPurchases    0
Purchase             0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                100 non-null    int64
 1   Income             100 non-null    int64
 2   PreviousPurchases  100 non-null    int64
 3   Purchase           100 non-null    int64
dtypes: int64(4)
memory usage: 3.3 KB

In [6]:
X = df[['Age', 'Income', 'PreviousPurchases']]
y = df['Purchase']

print("Input features:")
print(X.head())

print("\nTarget:")
print(y.head())

Input features:
   Age  Income  PreviousPurchases
0   22   25000                  1
1   25   30000                  2
2   28   35000                  3
3   30   40000                  4
4   32   45000                  5

Target:
0    0
1    0
2    0
3    1
4    1
Name: Purchase, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (80, 3)
Testing data: (20, 3)

In [8]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
logistic = LogisticRegression()

logistic.fit(X_train_scaled, y_train)

y_pred_logistic = logistic.predict(X_test_scaled)

In [10]:
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)
precision_logistic = precision_score(y_test, y_pred_logistic)
recall_logistic = recall_score(y_test, y_pred_logistic)

print("Logistic Regression")
print("Accuracy :", accuracy_logistic)
print("Precision:", precision_logistic)
print("Recall   :", recall_logistic)

Logistic Regression
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0

In [11]:
decision_tree = DecisionTreeClassifier(
    random_state=42,
    max_depth=4
)

decision_tree.fit(X_train, y_train)

y_pred_tree = decision_tree.predict(X_test)

In [12]:
accuracy_tree = accuracy_score(y_test, y_pred_tree)
precision_tree = precision_score(y_test, y_pred_tree)
recall_tree = recall_score(y_test, y_pred_tree)

print("Decision Tree")
print("Accuracy :", accuracy_tree)
print("Precision:", precision_tree)
print("Recall   :", recall_tree)

Decision Tree
Accuracy : 0.95
Precision: 0.9285714285714286
Recall   : 1.0

In [13]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [14]:
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)

print("K-Nearest Neighbour")
print("Accuracy :", accuracy_knn)
print("Precision:", precision_knn)
print("Recall   :", recall_knn)

K-Nearest Neighbour
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0

In [15]:
random_forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

random_forest.fit(X_train, y_train)

y_pred_forest = random_forest.predict(X_test)

In [16]:
accuracy_forest = accuracy_score(y_test, y_pred_forest)
precision_forest = precision_score(y_test, y_pred_forest)
recall_forest = recall_score(y_test, y_pred_forest)

print("Random Forest")
print("Accuracy :", accuracy_forest)
print("Precision:", precision_forest)
print("Recall   :", recall_forest)

Random Forest
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0

In [17]:
svm = SVC()

svm.fit(X_train_scaled, y_train)

y_pred_svm = svm.predict(X_test_scaled)

In [18]:
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
recall_svm = recall_score(y_test, y_pred_svm)

print("Support Vector Machine")
print("Accuracy :", accuracy_svm)
print("Precision:", precision_svm)
print("Recall   :", recall_svm)

Support Vector Machine
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0

In [19]:
results = pd.DataFrame({
    'Algorithm': [
        'Logistic Regression',
        'Decision Tree',
        'KNN',
        'Random Forest',
        'SVM'
    ],
    'Accuracy': [
        accuracy_logistic,
        accuracy_tree,
        accuracy_knn,
        accuracy_forest,
        accuracy_svm
    ],
    'Precision': [
        precision_logistic,
        precision_tree,
        precision_knn,
        precision_forest,
        precision_svm
    ],
    'Recall': [
        recall_logistic,
        recall_tree,
        recall_knn,
        recall_forest,
        recall_svm
    ]
})

results

             Algorithm  Accuracy  Precision  Recall
0  Logistic Regression      1.00   1.000000     1.0
1        Decision Tree      0.95   0.928571     1.0
2                  KNN      1.00   1.000000     1.0
3        Random Forest      1.00   1.000000     1.0
4                  SVM      1.00   1.000000     1.0

In [20]:
results_percentage = results.copy()

results_percentage[['Accuracy', 'Precision', 'Recall']] = (
    results_percentage[['Accuracy', 'Precision', 'Recall']] * 100
).round(2)

results_percentage

             Algorithm  Accuracy  Precision  Recall
0  Logistic Regression     100.0     100.00   100.0
1        Decision Tree      95.0      92.86   100.0
2                  KNN     100.0     100.00   100.0
3        Random Forest     100.0     100.00   100.0
4                  SVM     100.0     100.00   100.0