In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [26]:
df = pd.read_csv("house_price.csv")

df.head()

   Area  Bedrooms  Age    Price
0   800         2   10  1800000
1   850         2    8  1950000
2   900         2    7  2100000
3   950         2    6  2250000
4  1000         2    5  2400000

In [27]:
print("Dataset Shape:", df.shape)

print("\nDataset Information:")
print(df.info())

print("\nFirst 5 Rows:")
print(df.head())

Dataset Shape: (49, 4)

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Area      49 non-null     int64
 1   Bedrooms  49 non-null     int64
 2   Age       49 non-null     int64
 3   Price     49 non-null     int64
dtypes: int64(4)
memory usage: 1.7 KB
None

First 5 Rows:
   Area  Bedrooms  Age    Price
0   800         2   10  1800000
1   850         2    8  1950000
2   900         2    7  2100000
3   950         2    6  2250000
4  1000         2    5  2400000

In [28]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Area        0
Bedrooms    0
Age         0
Price       0
dtype: int64

In [29]:
X = df[['Area', 'Bedrooms', 'Age']]
y = df['Price']

print("Input Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Input Features:
   Area  Bedrooms  Age
0   800         2   10
1   850         2    8
2   900         2    7
3   950         2    6
4  1000         2    5

Target:
0    1800000
1    1950000
2    2100000
3    2250000
4    2400000
Name: Price, dtype: int64

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (39, 3)
Testing Data: (10, 3)

In [32]:
linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

y_pred_linear = linear_model.predict(X_test)

In [33]:
mae_linear = mean_absolute_error(y_test, y_pred_linear)
mse_linear = mean_squared_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mse_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print("Linear Regression")
print("MAE :", mae_linear)
print("MSE :", mse_linear)
print("RMSE:", rmse_linear)
print("R2 Score:", r2_linear)

Linear Regression
MAE : 48962.25955123608
MSE : 3279303125.2053933
RMSE: 57265.19994905626
R2 Score: 0.9990295120263374

In [34]:
poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

poly_model = LinearRegression()

poly_model.fit(X_train_poly, y_train)

y_pred_poly = poly_model.predict(X_test_poly)

In [35]:
mae_poly = mean_absolute_error(y_test, y_pred_poly)
mse_poly = mean_squared_error(y_test, y_pred_poly)
rmse_poly = np.sqrt(mse_poly)
r2_poly = r2_score(y_test, y_pred_poly)

print("Polynomial Regression")
print("MAE :", mae_poly)
print("MSE :", mse_poly)
print("RMSE:", rmse_poly)
print("R2 Score:", r2_poly)

Polynomial Regression
MAE : 19257.895681125905
MSE : 643029782.1181295
RMSE: 25358.0319054561
R2 Score: 0.999809699607988

In [36]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ridge_model = Ridge(alpha=1.0)

ridge_model.fit(X_train_scaled, y_train)

y_pred_ridge = ridge_model.predict(X_test_scaled)

In [37]:
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("Ridge Regression")
print("MAE :", mae_ridge)
print("MSE :", mse_ridge)
print("RMSE:", rmse_ridge)
print("R2 Score:", r2_ridge)

Ridge Regression
MAE : 135351.7309449032
MSE : 34355336523.67928
RMSE: 185351.92613965273
R2 Score: 0.9898327663975025

In [38]:
lasso_model = Lasso(alpha=0.1)

lasso_model.fit(X_train_scaled, y_train)

y_pred_lasso = lasso_model.predict(X_test_scaled)

In [39]:
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("Lasso Regression")
print("MAE :", mae_lasso)
print("MSE :", mse_lasso)
print("RMSE:", rmse_lasso)
print("R2 Score:", r2_lasso)

Lasso Regression
MAE : 48962.58202069187
MSE : 3279322358.0163817
RMSE: 57265.36787637343
R2 Score: 0.9990295063345147

In [40]:
tree_model = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_test)

In [41]:
mae_tree = mean_absolute_error(y_test, y_pred_tree)
mse_tree = mean_squared_error(y_test, y_pred_tree)
rmse_tree = np.sqrt(mse_tree)
r2_tree = r2_score(y_test, y_pred_tree)

print("Decision Tree Regression")
print("MAE :", mae_tree)
print("MSE :", mse_tree)
print("RMSE:", rmse_tree)
print("R2 Score:", r2_tree)

Decision Tree Regression
MAE : 221666.6666666667
MSE : 53277777777.777794
RMSE: 230819.79503018755
R2 Score: 0.984232795620696

In [42]:
forest_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

forest_model.fit(X_train, y_train)

y_pred_forest = forest_model.predict(X_test)

In [43]:
mae_forest = mean_absolute_error(y_test, y_pred_forest)
mse_forest = mean_squared_error(y_test, y_pred_forest)
rmse_forest = np.sqrt(mse_forest)
r2_forest = r2_score(y_test, y_pred_forest)

print("Random Forest Regression")
print("MAE :", mae_forest)
print("MSE :", mse_forest)
print("RMSE:", rmse_forest)
print("R2 Score:", r2_forest)

Random Forest Regression
MAE : 164350.0
MSE : 33294175000.0
RMSE: 182466.9148092333
R2 Score: 0.9901468101005467

In [44]:
results = pd.DataFrame({
    'Algorithm': [
        'Linear Regression',
        'Polynomial Regression',
        'Ridge Regression',
        'Lasso Regression',
        'Decision Tree',
        'Random Forest'
    ],
    
    'MAE': [
        mae_linear,
        mae_poly,
        mae_ridge,
        mae_lasso,
        mae_tree,
        mae_forest
    ],
    
    'MSE': [
        mse_linear,
        mse_poly,
        mse_ridge,
        mse_lasso,
        mse_tree,
        mse_forest
    ],
    
    'RMSE': [
        rmse_linear,
        rmse_poly,
        rmse_ridge,
        rmse_lasso,
        rmse_tree,
        rmse_forest
    ],
    
    'R2 Score': [
        r2_linear,
        r2_poly,
        r2_ridge,
        r2_lasso,
        r2_tree,
        r2_forest
    ]
})

results

               Algorithm            MAE           MSE           RMSE  R2 Score
0      Linear Regression   48962.259551  3.279303e+09   57265.199949  0.999030
1  Polynomial Regression   19257.895681  6.430298e+08   25358.031905  0.999810
2       Ridge Regression  135351.730945  3.435534e+10  185351.926140  0.989833
3       Lasso Regression   48962.582021  3.279322e+09   57265.367876  0.999030
4          Decision Tree  221666.666667  5.327778e+10  230819.795030  0.984233
5          Random Forest  164350.000000  3.329418e+10  182466.914809  0.990147

In [45]:
results.sort_values(
    by='R2 Score',
    ascending=False
)

               Algorithm            MAE           MSE           RMSE  R2 Score
1  Polynomial Regression   19257.895681  6.430298e+08   25358.031905  0.999810
0      Linear Regression   48962.259551  3.279303e+09   57265.199949  0.999030
3       Lasso Regression   48962.582021  3.279322e+09   57265.367876  0.999030
5          Random Forest  164350.000000  3.329418e+10  182466.914809  0.990147
2       Ridge Regression  135351.730945  3.435534e+10  185351.926140  0.989833
4          Decision Tree  221666.666667  5.327778e+10  230819.795030  0.984233

In [ ]:
plt.figure(figsize=(10, 5))

plt.bar(
    results['Algorithm'],
    results['R2 Score']
)

plt.xlabel("Regression Algorithm")
plt.ylabel("R2 Score")
plt.title("Comparison of Regression Algorithms")

plt.xticks(rotation=45)
plt.show()